//
//  TestAnswer.swift
//  HSK Online Test
//
//  Created by Sorboni Mumin on 06.09.2024.
//

import Foundation

struct TestAnswer {
    static let level1 = [
        Answer(number: 1, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 2, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 3, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 4, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 5, type: .trueFalse, userAnswer: .trueFalse(nil)),
        
        Answer(number: 6, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 7, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 8, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 9, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 10, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 11, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 12, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 13, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 14, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 15, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 16, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 17, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 18, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 19, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 20, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 21, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 22, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 23, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 24, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 25, type: .trueFalse, userAnswer: .trueFalse(nil)),
        
        Answer(number: 26, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 27, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 28, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 29, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 30, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 31, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 32, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 33, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 34, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 35, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 36, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 37, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 38, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 39, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 40, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil))
    ]
    
    static let level2 = [
        Answer(number: 1, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 2, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 3, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 4, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 5, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 6, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 7, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 8, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 9, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 10, type: .trueFalse, userAnswer: .trueFalse(nil)),
        
        Answer(number: 11, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 12, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 13, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 14, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 15, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 16, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 17, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 18, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 19, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 20, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 21, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 22, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 23, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 24, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 25, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        
        Answer(number: 26, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 27, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 28, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 29, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 30, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 31, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 32, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 33, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 34, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 35, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 36, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 37, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 38, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 39, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 40, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 41, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 42, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 43, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 44, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 45, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 46, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 47, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 48, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 49, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 50, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 51, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 52, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 53, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 54, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 55, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 56, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 57, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 58, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 59, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 60, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil))
    ]
    
    static let level3 = [
        Answer(number: 1, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 2, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 3, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 4, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 5, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 6, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 7, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 8, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 9, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 10, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 11, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 12, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 13, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 14, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 15, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 16, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 17, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 18, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 19, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 20, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 21, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 22, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 23, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 24, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 25, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 26, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 27, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 28, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 29, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 30, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 31, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 32, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 33, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 34, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 35, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 36, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 37, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 38, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 39, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 40, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 41, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 42, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 43, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 44, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 45, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 46, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 47, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 48, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 49, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 50, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 51, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 52, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 53, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 54, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 55, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 56, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 57, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 58, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 59, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 60, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 61, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 62, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 63, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 64, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 65, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 66, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 67, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 68, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 69, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 70, type: .threeOptions(options: ["A", "B", "C"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 71, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 72, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 73, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 74, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 75, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 76, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 77, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 78, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 79, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 80, type: .textInput, userAnswer: .textInput(nil))
    ]
    
    static let level4 = [
        Answer(number: 1, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 2, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 3, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 4, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 5, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 6, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 7, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 8, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 9, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 10, type: .trueFalse, userAnswer: .trueFalse(nil)),
        Answer(number: 11, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 12, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 13, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 14, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 15, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 16, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 17, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 18, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 19, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 20, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 21, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 22, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 23, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 24, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 25, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 26, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 27, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 28, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 29, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 30, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 31, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 32, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 33, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 34, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 35, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 36, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 37, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 38, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 39, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 40, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 41, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 42, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 43, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 44, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 45, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 46, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 47, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 48, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 49, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 50, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 51, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 52, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 53, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 54, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 55, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 56, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 57, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 58, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 59, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 60, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 61, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 62, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 63, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 64, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 65, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 66, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 67, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 68, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 69, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 70, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 71, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 72, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 73, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 74, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 75, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 76, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 77, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 78, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 79, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 80, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 81, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 82, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 83, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 84, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 85, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 86, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 87, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 88, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 89, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 90, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 91, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 92, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 93, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 94, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 95, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 96, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 97, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 98, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 99, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 100, type: .textInput, userAnswer: .textInput(nil))
    ]
    
    static let level5 = [
        Answer(number: 1, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 2, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 3, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 4, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 5, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 6, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 7, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 8, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 9, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 10, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 11, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 12, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 13, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 14, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 15, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 16, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 17, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 18, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 19, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 20, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 21, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 22, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 23, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 24, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 25, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 26, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 27, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 28, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 29, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 30, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 31, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 32, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 33, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 34, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 35, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 36, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 37, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 38, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 39, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 40, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 41, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 42, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 43, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 44, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 45, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 46, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 47, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 48, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 49, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 50, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 51, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 52, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 53, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 54, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 55, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 56, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 57, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 58, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 59, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 60, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 61, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 62, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 63, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 64, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 65, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 66, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 67, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 68, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 69, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 70, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 71, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 72, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 73, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 74, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 75, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 76, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 77, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 78, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 79, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 80, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 81, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 82, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 83, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 84, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 85, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 86, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 87, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 88, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 89, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 90, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 91, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 92, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 93, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 94, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 95, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 96, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 97, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 98, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 99, type: .textInput, userAnswer: .textInput(nil)),
        Answer(number: 100, type: .textInput, userAnswer: .textInput(nil))
    ]
    
    static let level6 = [
        Answer(number: 1, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 2, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 3, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 4, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 5, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 6, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 7, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 8, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 9, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 10, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 11, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 12, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 13, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 14, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 15, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 16, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 17, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 18, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 19, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 20, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 21, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 22, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 23, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 24, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 25, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 26, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 27, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 28, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 29, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 30, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 31, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 32, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 33, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 34, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 35, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 36, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 37, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 38, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 39, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 40, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 41, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 42, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 43, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 44, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 45, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 46, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 47, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 48, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 49, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 50, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 51, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 52, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 53, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 54, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 55, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 56, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 57, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 58, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 59, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 60, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 61, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 62, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 63, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 64, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 65, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 66, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 67, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 68, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 69, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 70, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 71, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 72, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 73, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 74, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 75, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 76, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 77, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 78, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 79, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 80, type: .sixOptions(options: ["A", "B", "C", "D", "E", "F"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 81, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 82, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 83, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 84, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 85, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 86, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 87, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 88, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 89, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 90, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 91, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 92, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 93, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 94, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 95, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 96, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 97, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 98, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 99, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 100, type: .fourOptions(options: ["A", "B", "C", "D"]), userAnswer: .multipleChoice(nil)),
        Answer(number: 101, type: .textInput, userAnswer: .textInput(nil))
    ]
}
